let name="sher";
var age=20;
const height="6 feet";
let species="andhagadu";
console.log("name:", name);
console.log("age:", age);
console.log("height:", height);
console.log("species:", species);
document.write("name: " + name);
document.write("<br>");
document.write("age: " + age);
document.write("<br>");
document.write("height: " + height);
document.write("<br>");
document.write("species: " + species);  
console.log(age);
console .log(age+5);
console.log(age-3);
console.log(age*2);
console.log(age/2);
console.log(age%4);
age+=3;
console.log(age);
age-=2; 
console.log(age);
let age1=25;
console.log(age>age1);
console.log(age<age1);
console.log(age>=age1);   
console.log(age<=age1);
console.log(age==age1);
console.log(age!=age1);